https://www.deeplearningbook.org/contents/linear_algebra.html

### Matrix

### Vectors 
     e.g. a matrix of 3 rows and 1 cols or 1 row and 4 cols. 

### scalar    
e..g, [15], 1 row and 1 col 


## Declaring scalars, vectors, and matrices

### Importing the relevant libriaries 

In [1]:
import numpy as np

### Scalars

In [2]:
s = 5

In [3]:
s

5

### Vectors 

In [4]:
v = np.array([5,-2,4])

In [5]:
v


array([ 5, -2,  4])

### Matrices

In [6]:
m = np.array([[5,12,6],[-3,0,14]])

In [7]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### data types

In [8]:
type(s)

int

In [9]:
type(v)

numpy.ndarray

In [10]:
type(m)

numpy.ndarray

In [11]:
s_array = np.array(5)
s_array

array(5)

In [12]:
type(s_array)

numpy.ndarray

### data shapes

In [13]:
m.shape

(2, 3)

In [14]:
v

array([ 5, -2,  4])

In [15]:
v.shape

(3,)

In [16]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [17]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [18]:
s_array.shape    ## no shape

()

## Tensors

In [19]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [20]:
m2 =np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [21]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

### check its shape

In [22]:
t.shape

(2, 2, 3)

### Manually creating a tensor

In [23]:
t_mannual = np.array([[[5,12,6],[-3,0,14]], [[9,8,7],[1,3,-5]]])
t_mannual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [24]:
t_mannual.shape

(2, 2, 3)

<html><head>


<!-- Load require.js. Delete this if your page already loads require.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js" integrity="sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA=" crossorigin="anonymous"></script>
<script src="https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js" crossorigin="anonymous"></script>
<script type="application/vnd.jupyter.widget-state+json">
{
    "version_major": 2,
    "version_minor": 0,
    "state": {}
}
</script>
</head>
<body>

<img src="what is a Tensor.png" width='600'>

</body>
</html>


## Addition of matrices

In [25]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [26]:
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [27]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

### Subtraction 
m1 - m2

In [28]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

### Adding Vectors  

In [29]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [30]:
v1 + v2

array([6, 6, 6, 6, 6])

In [31]:
v1 - v2

array([-4, -2,  0,  2,  4])

### Excepts (Adding with a scalar)
for vectors and matrices, they must have the same dimension in order to add them together.

In [32]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [33]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [34]:
v1

array([1, 2, 3, 4, 5])

In [35]:
v1 + 1

array([2, 3, 4, 5, 6])

Although the above are allowed in Python, but they are not allowed in linear algebra. 

### Transpose a matrix

In [36]:
v1 = np.array([1,2,3])

In [37]:
v1.reshape(3,1)

array([[1],
       [2],
       [3]])

In [38]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [39]:
m1.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [40]:
B = np.array([[5,3],[-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [41]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [46]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [47]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

### Transposing scalars
A scalar is transposed to itself.

In [50]:
s = np.array(5)
s

array(5)

In [51]:
s.T

array(5)

In [52]:
### Transposing Vector

In [53]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [55]:
x.T

array([1, 2, 3])

In [56]:
x.shape

(3,)

In [58]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [59]:
x_reshaped.shape

(1, 3)

In [67]:
x_reshaped.T

array([[1],
       [2],
       [3]])

In [70]:
x1 = np.zeros((3,3))
x1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Dot product 

In [73]:
# Vector * Vector
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [74]:
np.dot(x,y)

-66

In [81]:
# Scalar * scalar
s1 = np.array(5)
s2 = np.array(6)
s_dot = np.dot(s1,s2)
s_dot, s_dot.shape

(30, ())

In [87]:
# Scalar * Vector
np.dot(s1, x)

array([ 10,  40, -20])

In [88]:
# Scalar * Matrix
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [89]:
np.dot(s1, A)

array([[ 25,  60,  30],
       [-15,   0,  70]])

In [90]:
# Matrix * Matrix
M1 = np.array([[5,12,6], [-3,0,14]])
M2 = np.array([[2,-1],[8,0],[3,0]])

In [91]:
np.dot(M1, M2)

array([[124,  -5],
       [ 36,   3]])

In [93]:
np.dot(M2, M1)

array([[13, 24, -2],
       [40, 96, 48],
       [15, 36, 18]])