## Train Test Split

### Import the libraries

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

### Generate some date we are going to split

In [6]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
b = np.arange(501, 601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

### Split the data

In [8]:
train_test_split(a)

[array([88, 44, 17, 77, 73, 57, 19, 54, 27, 69,  2, 31, 85, 22, 23, 24, 67,
        89, 47,  3, 87, 32, 45, 46, 41, 68, 72, 71, 53, 30, 55, 63, 58,  9,
        76, 38, 34, 64, 40, 37, 18, 26, 80, 14, 96, 61, 33, 49, 98, 13, 74,
         8, 93, 97, 86, 90, 29, 99, 36, 15, 95,  6, 25,  7, 43, 21, 28,  1,
        91, 56, 60, 12, 66, 75, 20]),
 array([ 42,  48,  51,  83,  52,  82,  84,  70,  62,  59,  11,  65,  94,
         50,  16,   4,  92,  39,  78,  35,  79, 100,  10,   5,  81])]

In [36]:
a_train,a_test,b_train,b_test = train_test_split(a, b, test_size=0.2, random_state=42)
# test_size=0.2, should be avalue (0-1)
# shuffle: default is True, can set it to False for time series, etc.
# random_state: 42 is often used

### Explore the data

In [38]:
a_train.shape, a_test.shape

((80,), (20,))

In [39]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [40]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [41]:
b_train.shape, b_test.shape

((80,), (20,))

In [42]:
b_train

array([556, 589, 527, 543, 570, 516, 541, 597, 510, 573, 512, 548, 586,
       529, 594, 506, 567, 566, 536, 517, 550, 535, 508, 596, 528, 520,
       582, 526, 563, 514, 525, 504, 518, 539, 509, 579, 507, 565, 537,
       590, 557, 600, 555, 544, 551, 568, 547, 569, 562, 598, 580, 542,
       559, 549, 599, 558, 576, 533, 595, 560, 564, 585, 538, 530, 502,
       553, 522, 503, 524, 588, 592, 575, 587, 583, 521, 561, 572, 515,
       593, 552])

In [43]:
b_test

array([584, 554, 571, 546, 545, 540, 523, 581, 511, 501, 519, 531, 574,
       534, 591, 505, 577, 578, 513, 532])